### ISSUE TITLE
Attestation Statement Error

### ISSUE THREAD

**Issue by maraino** [brandonweeks/draft-bweeks-acme-device-attest#5]
### Description

ACME RFC [section-6.7](https://www.rfc-editor.org/rfc/rfc8555#section-6.7) defines some standard errors. A device attestation error should be defined, something like:

| Type | Description
| --- | --- |
| badAttestationStatement | Attestation statement cannot be verified |

**Comment by brandonweeks** [comment]
Added in fdc5aac.

**Comment by brandonweeks** [comment]
Incorporated into https://datatracker.ietf.org/doc/draft-acme-device-attest/01/.
